server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/web
    username: beyond          # 본인 계정
    password: beyond        # 본인 비번
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update      # 초기 개발은 update, 운영은 validate/Flyway 권장
    show-sql: true
    properties:
      hibernate.format_sql: true
